version: '3'
services:
  db-master:
    container_name: db-master
    image: urlund/percona:replication
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pass
      - MYSQL_REPLICATION_ROLE=master
    volumes:
      - /path/to/master.cnf:/etc/mysql/conf.d/master.cnf
      - /path/to/mysql/:/var/lib/mysql/
  db-slave:
    container_name: db-slave
    image: urlund/percona:replication
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pass
      - MYSQL_REPLICATION_ROLE=slave
    volumes:
      - /path/to/slave.cnf:/etc/mysql/conf.d/slave.cnf
      - /path/to/mysql/:/var/lib/mysql/
